### ISSUE TITLE
Handling styles based on toolbar.

### ISSUE THREAD

**Issue by MohitKS5** [BomdiZane/EditorJS-React-Renderer#5]
How can I set width of image without disturbing the stretch button ? What happens now is if I set the width to '80%', pressing the stretch button does nothing in renderer. What should happen is width is overridden to '100%.

**Comment by dev-juju** [comment]
@MohitKS5 for any similar issues in future, please note that by design, user defined styles take priority over default and/or codex styles.
However, in this case we see enough valid use cases and have added this change as part of [v2.2.0](https://www.npmjs.com/package/editorjs-react-renderer). 

Thanks for raising this
