### ISSUE TITLE
Doesn't work with Next and SSR

### ISSUE THREAD

**Issue by maximelebreton** [BomdiZane/EditorJS-React-Renderer#69]
Hello @dev-juju, and thanks for your work!

I've found how to make your `v3` plugin working on **Next** in **client** mode, with your code here: 
https://github.com/dev-juju/EditorJS-React-Renderer/issues/43#issuecomment-1074016021

<details>
<summary>and this on <code>next.config.js</code>:</summary>

```js
{
//...
webpack(config, { webpack }) {
    config.plugins.push(
      new webpack.ProvidePlugin({
        React: "react",
      })
    )
    return config
  }
}
```
</details>

But it doesn't work in **server** mode: `Error: React is not defined`

I don't know if the reduced bundle size of `v3`  is only the drop of **React**,
but if if I'm ok ton include **React** as a dependency, is there a way to tell your plugin to call the **React** dependency and make **SSR** work again©?

`"editorjs-react-renderer": "^3.5.0-beta.3"`
`"next": "12.3.1"`
`"react": "^18.2.0"`

Thanks!

**Comment by dev-juju** [comment]
@maximelebreton 

Please update to V3.5.0, there are some issues with the beta versions

By default you shouldn’t have reference error client-side.
V3 cannot work server-side. Since you're using Nextjs your easiest option would be to turn off SSR with dynamic imports.

V4 will most probably work server-side but I can't give you an ETC on that at this time.
